### ISSUE TITLE
Yosys uhdm frontend generates incorrect AST for the 'for' loop.

### ISSUE THREAD

**Issue by kamilrakoczy** [alainmarcel/uhdm-integration#50]
Yosys uhdm frontend wrong generates AST for 'for' loop, it automatically simplify expressions to AST_CONSTANT, but simplify expects, that this expression will be AST_IDENTIFIER.

**Comment by kbieganski** [comment]
Should work for at least some cases after this:
https://github.com/antmicro/yosys/commit/a97a177f9cf1dff95a73c4b5b9ee9d0f743992c3#diff-974349ca5d1dd48f4fbe86dd58c4908830990d8a2272ba93c9317b4de512f78a

**Comment by kbieganski** [comment]
Fixed in `uhdm-yosys`.
