### ISSUE TITLE
Yosys frontend sometimes wrongly parses parameters

### ISSUE THREAD

**Issue by kamilrakoczy** [alainmarcel/uhdm-integration#51]
Assignment-patterns AST differs when used in parameters parameters (there is no AST_ASSIGN when assigning to parameter). Currently yosys frontend fails on parsing this type of parameters and creates parameter without any children. This ends up with segmentation fault.

**Comment by kbieganski** [comment]
Should work for at least some cases after this:
https://github.com/antmicro/yosys/commit/a97a177f9cf1dff95a73c4b5b9ee9d0f743992c3#diff-974349ca5d1dd48f4fbe86dd58c4908830990d8a2272ba93c9317b4de512f78a

**Comment by kamilrakoczy** [comment]
Yes, this commit fixes some cases of segmentation fault, but there are also other cases that causes segmentation fault  when parsing parameters (not necessary related to assignment patterns).
